# Generated by Django 4.1.7 on 2023-04-02 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='height',
        ),
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.RemoveField(
            model_name='account',
            name='image_ratio',
        ),
        migrations.RemoveField(
            model_name='account',
            name='width',
        ),
        migrations.RemoveField(
            model_name='account',
            name='x',
        ),
        migrations.RemoveField(
            model_name='account',
            name='y',
        ),
    ]
